[formatter.nix]
command = "nix"
options = [
  "fmt",
]
includes = [
  "*.nix",
]

[formatter.py]
command = "black"
options = [
  "--line-length=79",
]
includes = [
  "*.py",
]

[formatter.py-lint]
command = "ruff"
options = [
  "check",
]
includes = [
  "*.py",
]

[global]
excludes = [
  "*.lock",
  ".editorconfig",
  ".gitignore",
  ".gitmodules",
  "LICENSE.md",
  "site_scons/site_tools/github/jacobkoziej/scons-tools",
]
