[formatter.md]
command = "mdformat"
options = [
  "--number",
  "--wrap=72",
]
includes = [
  "*.md",
]

[formatter.nix]
command = "nix"
options = [
  "fmt",
]
includes = [
  "*.nix",
]

[formatter.py]
command = "black"
options = [
  "--line-length=79",
]
includes = [
  "*.py",
]

[formatter.py-lint]
command = "ruff"
options = [
  "check",
]
includes = [
  "*.py",
]

[formatter.toml]
command = "toml-sort"
options = [
  "--in-place",
  "--trailing-comma-inline-array",
]
includes = [
  "*.toml",
]

[global]
excludes = [
  "*.lock",
  ".editorconfig",
  ".gitignore",
  ".gitmodules",
  "LICENSE.md",
  "site_scons/site_tools/github/jacobkoziej/scons-tools",
]
